apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: poc-icbs
  description: Sistema Core Banking Integrado - Oracle WebLogic
  annotations:
    github.com/project-slug: giovanemere/poc-icbs
    backstage.io/techdocs-ref: dir:.
  tags:
    - backend
    - spring-boot
    - poc
    - billpay
spec:
  type: service
  lifecycle: experimental
  owner: ia-ops-team
  system: billpay-system
  providesApis:
    - poc-icbs-api
  consumesApis:
    - database-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: poc-icbs-api
  description: REST API for poc-icbs
spec:
  type: openapi
  lifecycle: experimental
  owner: ia-ops-team
  system: billpay-system
