site_name: 'poc-icbs Documentation'
site_description: 'Documentación del proyecto poc-icbs'

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Deployment: deployment.md

plugins:
  - techdocs-core

theme:
  name: material
  palette:
    primary: blue
    accent: blue

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
