FROM nginx:alpine

# Copiar sitio construido
COPY site/ /usr/share/nginx/html/

# Configuración nginx para MkDocs
COPY nginx/mkdocs.conf /etc/nginx/conf.d/default.conf

EXPOSE 8000

CMD ["nginx", "-g", "daemon off;"]
